version: "3.8"

services:

  backend:
    container_name: xaibio-backend
    build:
      context: ./xaibio-backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    container_name: xaibio-frontend
    build:
      context: ./xaibio-frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    volumes:
      - ./xaibio-frontend/dist:/app/dist
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./xaibio-frontend/dist:/frontend
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:13.1
    ports:
      - 5432:5432
    logging:
      driver: none
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
