version: "3.8"

services:

  backend:
    container_name: xaibio-backend
    build:
      context: ./xaibio-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./xaibio-backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - postgres

  frontend:
    container_name: xaibio-frontend
    build:
      context: ./xaibio-frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./xaibio-frontend/src:/app/src
    env_file:
      - .env.dev
    depends_on:
      - backend 

  postgres:
    image: postgres:13.1
    ports:
      - 5432:5432
    logging:
      driver: none
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 16543:80
    logging:
      driver: none
    env_file:
      - .env.dev
    depends_on:
      - postgres