FROM python:3.12

WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Upgrade pip
RUN pip install --upgrade pip

# Copy and install Python dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Set default command
CMD exec python manage.py runserver 0.0.0.0:8000