# Generated by Django 5.0.4 on 2024-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.IntegerField()),
                ('age', models.IntegerField()),
                ('nose', models.IntegerField()),
                ('skin_tone', models.IntegerField()),
            ],
        ),
    ]
