# Generated by Django 5.0.4 on 2024-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_featuredimage_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('embedding', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FeaturedImage',
        ),
    ]
