# Generated by Django 5.0.4 on 2024-04-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_image_delete_featuredimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='path',
        ),
    ]
