# Generated by Django 5.0.4 on 2024-04-24 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_url_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
