# Generated by Django 5.0.4 on 2024-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_image_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_feature_example',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_identification_example',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_verification_example',
            field=models.BooleanField(default=False),
        ),
    ]
