# Generated by Django 5.0.4 on 2024-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_image_is_feature_example_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id',
            new_name='img_id',
        ),
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='user_name',
            field=models.CharField(default='carol', max_length=100),
            preserve_default=False,
        ),
    ]
