# Generated by Django 5.0.4 on 2024-05-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_image_img_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_example',
        ),
    ]
