# Generated by Django 5.0.4 on 2024-05-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_remove_image_is_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_hash',
            new_name='hash',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_name',
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
    ]
